"""
Seed Data Loader — IPI Consent Decree Dashboard

Loads well-known major CWA/SDWA municipal wastewater consent decrees
into BigQuery using the same MERGE/UPSERT pattern as the main ETL.

Usage:
    python seed_data.py
"""

import os
import time
from datetime import date, datetime

from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# BigQuery schema (mirrors etl.py)
# ---------------------------------------------------------------------------

BQ_SCHEMA = [
    ("case_number", "STRING"),
    ("registry_id", "STRING"),
    ("fips_code", "STRING"),
    ("facility_name", "STRING"),
    ("city", "STRING"),
    ("state", "STRING"),
    ("zip_code", "STRING"),
    ("county", "STRING"),
    ("consent_decree_date", "DATE"),
    ("compliance_end_date", "DATE"),
    ("lead_agency", "STRING"),
    ("enforcement_level", "STRING"),
    ("action_type", "STRING"),
    ("violation_type", "STRING"),
    ("penalty_amount", "FLOAT64"),
    ("statute", "STRING"),
    ("pipe_infrastructure_flag", "BOOL"),
    ("population", "INT64"),
    ("days_to_deadline", "INT64"),
    ("urgency_tier", "STRING"),
    ("case_status", "STRING"),
    ("latitude", "FLOAT64"),
    ("longitude", "FLOAT64"),
    ("last_updated", "TIMESTAMP"),
]

# ---------------------------------------------------------------------------
# Reference date for days_to_deadline calculation
# ---------------------------------------------------------------------------

TODAY = date(2026, 3, 25)
NOW_TS = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def calc_urgency(compliance_end_date_str: str) -> tuple:
    """Return (days_to_deadline, urgency_tier) based on compliance_end_date."""
    end = date.fromisoformat(compliance_end_date_str)
    days = (end - TODAY).days
    if days < 0:
        tier = "OVERDUE"
    elif days <= 365:
        tier = "CRITICAL"
    elif days <= 1095:
        tier = "ACTIVE"
    else:
        tier = "MONITORING"
    return days, tier


# ---------------------------------------------------------------------------
# Seed consent decrees — real EPA CWA enforcement cases
# ---------------------------------------------------------------------------

RAW_DECREES = [
    # ---- Atlanta, GA — CSO/SSO (1998) ----
    {
        "case_number": "1:98-cv-01956",
        "registry_id": "110000465735",
        "fips_code": "13121",
        "facility_name": "City of Atlanta — Department of Watershed Management",
        "city": "Atlanta",
        "state": "GA",
        "zip_code": "30303",
        "county": "Fulton",
        "consent_decree_date": "1998-10-05",
        "compliance_end_date": "2027-12-31",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO/CSO",
        "penalty_amount": 2500000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 498715,
        "latitude": 33.749,
        "longitude": -84.388,
    },
    # ---- Baltimore, MD — SSO (2002) ----
    {
        "case_number": "1:02-cv-01524",
        "registry_id": "110000489262",
        "fips_code": "24510",
        "facility_name": "City of Baltimore — Department of Public Works",
        "city": "Baltimore",
        "state": "MD",
        "zip_code": "21202",
        "county": "Baltimore City",
        "consent_decree_date": "2002-08-22",
        "compliance_end_date": "2030-12-31",
        "lead_agency": "EPA Region 3",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 750000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 585708,
        "latitude": 39.2904,
        "longitude": -76.6122,
    },
    # ---- Houston, TX — SSO (2010) ----
    {
        "case_number": "4:10-cv-03606",
        "registry_id": "110007549811",
        "fips_code": "48201",
        "facility_name": "City of Houston — Public Works and Engineering",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77002",
        "county": "Harris",
        "consent_decree_date": "2010-10-07",
        "compliance_end_date": "2025-10-07",
        "lead_agency": "EPA Region 6",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 5500000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 2304580,
        "latitude": 29.7604,
        "longitude": -95.3698,
    },
    # ---- Indianapolis, IN — CSO (2006) ----
    {
        "case_number": "1:06-cv-1456",
        "registry_id": "110000539990",
        "fips_code": "18097",
        "facility_name": "City of Indianapolis — Department of Public Works",
        "city": "Indianapolis",
        "state": "IN",
        "zip_code": "46204",
        "county": "Marion",
        "consent_decree_date": "2006-01-18",
        "compliance_end_date": "2025-12-31",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 550000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 887642,
        "latitude": 39.7684,
        "longitude": -86.1581,
    },
    # ---- Louisville, KY — SSO/CSO (2005) ----
    {
        "case_number": "3:05-cv-00197",
        "registry_id": "110004302855",
        "fips_code": "21111",
        "facility_name": "Louisville/Jefferson County Metropolitan Sewer District",
        "city": "Louisville",
        "state": "KY",
        "zip_code": "40202",
        "county": "Jefferson",
        "consent_decree_date": "2005-08-16",
        "compliance_end_date": "2028-12-31",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO/CSO",
        "penalty_amount": 725000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 633045,
        "latitude": 38.2527,
        "longitude": -85.7585,
    },
    # ---- Kansas City, MO — CSO/SSO (2010) ----
    {
        "case_number": "4:10-cv-00497",
        "registry_id": "110001918610",
        "fips_code": "29095",
        "facility_name": "City of Kansas City — Water Services Department",
        "city": "Kansas City",
        "state": "MO",
        "zip_code": "64106",
        "county": "Jackson",
        "consent_decree_date": "2010-05-18",
        "compliance_end_date": "2035-05-18",
        "lead_agency": "EPA Region 7",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 600000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 508090,
        "latitude": 39.0997,
        "longitude": -94.5786,
    },
    # ---- Nashville, TN — CSO/SSO (2009) ----
    {
        "case_number": "3:09-cv-00267",
        "registry_id": "110000494771",
        "fips_code": "47037",
        "facility_name": "Metropolitan Government of Nashville and Davidson County",
        "city": "Nashville",
        "state": "TN",
        "zip_code": "37201",
        "county": "Davidson",
        "consent_decree_date": "2009-04-02",
        "compliance_end_date": "2031-04-02",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 1200000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 689447,
        "latitude": 36.1627,
        "longitude": -86.7816,
    },
    # ---- Jackson, MS — Drinking water crisis (2012/2020) ----
    {
        "case_number": "3:12-cv-00790",
        "registry_id": "110008149932",
        "fips_code": "28049",
        "facility_name": "City of Jackson — Water/Sewer Utilities Division",
        "city": "Jackson",
        "state": "MS",
        "zip_code": "39201",
        "county": "Hinds",
        "consent_decree_date": "2012-12-18",
        "compliance_end_date": "2024-12-18",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO / SDWA",
        "penalty_amount": 925000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 153701,
        "latitude": 32.2988,
        "longitude": -90.1848,
    },
    # ---- St. Louis MSD — CSO (2012) ----
    {
        "case_number": "4:07-cv-01120",
        "registry_id": "110000457621",
        "fips_code": "29510",
        "facility_name": "Metropolitan St. Louis Sewer District",
        "city": "St. Louis",
        "state": "MO",
        "zip_code": "63103",
        "county": "St. Louis City",
        "consent_decree_date": "2012-04-27",
        "compliance_end_date": "2035-04-27",
        "lead_agency": "EPA Region 7",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 4700000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 301578,
        "latitude": 38.627,
        "longitude": -90.1994,
    },
    # ---- Cleveland, OH — CSO (2010) ----
    {
        "case_number": "1:10-cv-02895",
        "registry_id": "110000413510",
        "fips_code": "39035",
        "facility_name": "Northeast Ohio Regional Sewer District",
        "city": "Cleveland",
        "state": "OH",
        "zip_code": "44115",
        "county": "Cuyahoga",
        "consent_decree_date": "2010-07-07",
        "compliance_end_date": "2035-07-07",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 8000000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 372624,
        "latitude": 41.4993,
        "longitude": -81.6944,
    },
    # ---- Cincinnati, OH — SSO (2002) ----
    {
        "case_number": "1:02-cv-00107",
        "registry_id": "110000407723",
        "fips_code": "39061",
        "facility_name": "Metropolitan Sewer District of Greater Cincinnati",
        "city": "Cincinnati",
        "state": "OH",
        "zip_code": "45202",
        "county": "Hamilton",
        "consent_decree_date": "2002-06-10",
        "compliance_end_date": "2028-12-31",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1100000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 309317,
        "latitude": 39.1031,
        "longitude": -84.512,
    },
    # ---- Pittsburgh, PA — ALCOSAN CSO (2008) ----
    {
        "case_number": "2:08-cv-00269",
        "registry_id": "110000402618",
        "fips_code": "42003",
        "facility_name": "Allegheny County Sanitary Authority (ALCOSAN)",
        "city": "Pittsburgh",
        "state": "PA",
        "zip_code": "15222",
        "county": "Allegheny",
        "consent_decree_date": "2008-01-23",
        "compliance_end_date": "2036-01-23",
        "lead_agency": "EPA Region 3",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 1250000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 302971,
        "latitude": 40.4406,
        "longitude": -79.9959,
    },
    # ---- New Orleans, LA — SSO (2013) ----
    {
        "case_number": "2:13-cv-06545",
        "registry_id": "110000458333",
        "fips_code": "22071",
        "facility_name": "Sewerage and Water Board of New Orleans",
        "city": "New Orleans",
        "state": "LA",
        "zip_code": "70112",
        "county": "Orleans",
        "consent_decree_date": "2013-06-19",
        "compliance_end_date": "2030-06-19",
        "lead_agency": "EPA Region 6",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 700000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 383997,
        "latitude": 29.9511,
        "longitude": -90.0715,
    },
    # ---- Memphis, TN — SSO (2012) ----
    {
        "case_number": "2:12-cv-02040",
        "registry_id": "110000460126",
        "fips_code": "47157",
        "facility_name": "City of Memphis — Public Works Division",
        "city": "Memphis",
        "state": "TN",
        "zip_code": "38103",
        "county": "Shelby",
        "consent_decree_date": "2012-02-17",
        "compliance_end_date": "2027-02-17",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1400000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 633104,
        "latitude": 35.1495,
        "longitude": -90.049,
    },
    # ---- Birmingham, AL — SSO (1996) ----
    {
        "case_number": "2:96-cv-00530",
        "registry_id": "110000437223",
        "fips_code": "01073",
        "facility_name": "Jefferson County (Birmingham) Sewer System",
        "city": "Birmingham",
        "state": "AL",
        "zip_code": "35203",
        "county": "Jefferson",
        "consent_decree_date": "1996-11-15",
        "compliance_end_date": "2023-12-31",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 850000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 200733,
        "latitude": 33.5207,
        "longitude": -86.8025,
    },
    # ---- Columbus, OH — SSO/CSO (2002) ----
    {
        "case_number": "2:02-cv-00527",
        "registry_id": "110000409912",
        "fips_code": "39049",
        "facility_name": "City of Columbus — Division of Sewerage and Drainage",
        "city": "Columbus",
        "state": "OH",
        "zip_code": "43215",
        "county": "Franklin",
        "consent_decree_date": "2002-09-05",
        "compliance_end_date": "2026-12-31",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO/CSO",
        "penalty_amount": 750000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 905748,
        "latitude": 39.9612,
        "longitude": -82.9988,
    },
    # ---- Akron, OH — CSO (2009) ----
    {
        "case_number": "5:09-cv-00272",
        "registry_id": "110000413102",
        "fips_code": "39153",
        "facility_name": "City of Akron — Sewer System",
        "city": "Akron",
        "state": "OH",
        "zip_code": "44308",
        "county": "Summit",
        "consent_decree_date": "2009-12-15",
        "compliance_end_date": "2028-12-15",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 510000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 190469,
        "latitude": 41.0814,
        "longitude": -81.519,
    },
    # ---- Toledo, OH — CSO (2002) ----
    {
        "case_number": "3:02-cv-07632",
        "registry_id": "110000411320",
        "fips_code": "39095",
        "facility_name": "City of Toledo — Division of Water Reclamation",
        "city": "Toledo",
        "state": "OH",
        "zip_code": "43604",
        "county": "Lucas",
        "consent_decree_date": "2002-04-30",
        "compliance_end_date": "2026-04-30",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 370000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 270871,
        "latitude": 41.6528,
        "longitude": -83.5379,
    },
    # ---- Savannah, GA — SSO (2004) ----
    {
        "case_number": "4:04-cv-00141",
        "registry_id": "110000465288",
        "fips_code": "13051",
        "facility_name": "City of Savannah — Water and Sewer Bureau",
        "city": "Savannah",
        "state": "GA",
        "zip_code": "31401",
        "county": "Chatham",
        "consent_decree_date": "2004-07-21",
        "compliance_end_date": "2025-07-21",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 335000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 147780,
        "latitude": 32.0809,
        "longitude": -81.0912,
    },
    # ---- Chattanooga, TN — CSO (2010) ----
    {
        "case_number": "1:10-cv-00186",
        "registry_id": "110000494055",
        "fips_code": "47065",
        "facility_name": "City of Chattanooga — Wastewater System",
        "city": "Chattanooga",
        "state": "TN",
        "zip_code": "37402",
        "county": "Hamilton",
        "consent_decree_date": "2010-09-30",
        "compliance_end_date": "2027-09-30",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 600000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 181099,
        "latitude": 35.0456,
        "longitude": -85.3097,
    },
    # ---- East Cleveland, OH — SSO (2012) ----
    {
        "case_number": "1:12-cv-01833",
        "registry_id": "110000413522",
        "fips_code": "39035",
        "facility_name": "City of East Cleveland — Sewer System",
        "city": "East Cleveland",
        "state": "OH",
        "zip_code": "44112",
        "county": "Cuyahoga",
        "consent_decree_date": "2012-09-25",
        "compliance_end_date": "2024-09-25",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 165000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 17307,
        "latitude": 41.533,
        "longitude": -81.5794,
    },
    # ---- Gary, IN — CSO/SSO (2004) ----
    {
        "case_number": "2:04-cv-00185",
        "registry_id": "110000539771",
        "fips_code": "18089",
        "facility_name": "Gary Sanitary District",
        "city": "Gary",
        "state": "IN",
        "zip_code": "46402",
        "county": "Lake",
        "consent_decree_date": "2004-02-23",
        "compliance_end_date": "2025-02-23",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 275000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 69093,
        "latitude": 41.5934,
        "longitude": -87.3464,
    },
    # ---- Detroit, MI — CSO/SSO (2011) ----
    {
        "case_number": "2:11-cv-10080",
        "registry_id": "110000521890",
        "fips_code": "26163",
        "facility_name": "Detroit Water and Sewerage Department",
        "city": "Detroit",
        "state": "MI",
        "zip_code": "48226",
        "county": "Wayne",
        "consent_decree_date": "2011-06-07",
        "compliance_end_date": "2029-06-07",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 3800000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 639111,
        "latitude": 42.3314,
        "longitude": -83.0458,
    },
    # ---- Washington, DC — CSO (2005) ----
    {
        "case_number": "1:00-cv-00183",
        "registry_id": "110000401122",
        "fips_code": "11001",
        "facility_name": "DC Water and Sewer Authority (DC Water)",
        "city": "Washington",
        "state": "DC",
        "zip_code": "20001",
        "county": "District of Columbia",
        "consent_decree_date": "2005-10-14",
        "compliance_end_date": "2030-10-14",
        "lead_agency": "EPA Region 3",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 1850000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 689545,
        "latitude": 38.9072,
        "longitude": -77.0369,
    },
    # ---- San Juan, PR — PRASA SSO (2015) ----
    {
        "case_number": "3:15-cv-02283",
        "registry_id": "110070665867",
        "fips_code": "72127",
        "facility_name": "Puerto Rico Aqueduct and Sewer Authority (PRASA)",
        "city": "San Juan",
        "state": "PR",
        "zip_code": "00901",
        "county": "San Juan",
        "consent_decree_date": "2015-06-09",
        "compliance_end_date": "2030-06-09",
        "lead_agency": "EPA Region 2",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO / SDWA",
        "penalty_amount": 6700000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 350000,
        "latitude": 18.4655,
        "longitude": -66.1057,
    },
    # ---- Honolulu, HI — SSO (2010) ----
    {
        "case_number": "1:09-cv-00091",
        "registry_id": "110000476211",
        "fips_code": "15003",
        "facility_name": "City and County of Honolulu — Wastewater System",
        "city": "Honolulu",
        "state": "HI",
        "zip_code": "96813",
        "county": "Honolulu",
        "consent_decree_date": "2010-12-16",
        "compliance_end_date": "2028-12-16",
        "lead_agency": "EPA Region 9",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1400000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 350964,
        "latitude": 21.3069,
        "longitude": -157.8583,
    },
    # ---- Miami-Dade, FL — SSO (2013) ----
    {
        "case_number": "1:12-cv-24400",
        "registry_id": "110000463801",
        "fips_code": "12086",
        "facility_name": "Miami-Dade County — Water and Sewer Department",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33128",
        "county": "Miami-Dade",
        "consent_decree_date": "2013-05-14",
        "compliance_end_date": "2027-05-14",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1550000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 2701767,
        "latitude": 25.7617,
        "longitude": -80.1918,
    },
    # ---- Los Angeles, CA — SSO (2004) ----
    {
        "case_number": "2:04-cv-09465",
        "registry_id": "110000476330",
        "fips_code": "06037",
        "facility_name": "City of Los Angeles — Bureau of Sanitation",
        "city": "Los Angeles",
        "state": "CA",
        "zip_code": "90012",
        "county": "Los Angeles",
        "consent_decree_date": "2004-11-02",
        "compliance_end_date": "2026-11-02",
        "lead_agency": "EPA Region 9",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 2200000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 3898747,
        "latitude": 34.0522,
        "longitude": -118.2437,
    },
    # ---- San Francisco, CA — CSO (2009) ----
    {
        "case_number": "3:09-cv-02651",
        "registry_id": "110000476225",
        "fips_code": "06075",
        "facility_name": "San Francisco Public Utilities Commission",
        "city": "San Francisco",
        "state": "CA",
        "zip_code": "94103",
        "county": "San Francisco",
        "consent_decree_date": "2009-06-23",
        "compliance_end_date": "2030-06-23",
        "lead_agency": "EPA Region 9",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 950000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 873965,
        "latitude": 37.7749,
        "longitude": -122.4194,
    },
    # ---- Philadelphia, PA — CSO (2012) ----
    {
        "case_number": "2:12-cv-05520",
        "registry_id": "110000402503",
        "fips_code": "42101",
        "facility_name": "City of Philadelphia — Water Department",
        "city": "Philadelphia",
        "state": "PA",
        "zip_code": "19107",
        "county": "Philadelphia",
        "consent_decree_date": "2012-03-08",
        "compliance_end_date": "2036-03-08",
        "lead_agency": "EPA Region 3",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 1250000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 1603797,
        "latitude": 39.9526,
        "longitude": -75.1652,
    },
    # ---- Omaha, NE — CSO (2009) ----
    {
        "case_number": "8:09-cv-00348",
        "registry_id": "110001920034",
        "fips_code": "31055",
        "facility_name": "City of Omaha — Public Works Department",
        "city": "Omaha",
        "state": "NE",
        "zip_code": "68102",
        "county": "Douglas",
        "consent_decree_date": "2009-10-08",
        "compliance_end_date": "2037-10-08",
        "lead_agency": "EPA Region 7",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 550000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 486051,
        "latitude": 41.2565,
        "longitude": -95.9345,
    },
    # ---- Knoxville, TN — CSO/SSO (2005) ----
    {
        "case_number": "3:05-cv-00413",
        "registry_id": "110000494901",
        "fips_code": "47093",
        "facility_name": "City of Knoxville — Wastewater Collection System",
        "city": "Knoxville",
        "state": "TN",
        "zip_code": "37902",
        "county": "Knox",
        "consent_decree_date": "2005-11-29",
        "compliance_end_date": "2025-11-29",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 275000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 190740,
        "latitude": 35.9606,
        "longitude": -83.9207,
    },
    # ---- Richmond, VA — CSO (2007) ----
    {
        "case_number": "3:07-cv-00503",
        "registry_id": "110000401533",
        "fips_code": "51760",
        "facility_name": "City of Richmond — Department of Public Utilities",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "county": "Richmond City",
        "consent_decree_date": "2007-03-22",
        "compliance_end_date": "2025-03-22",
        "lead_agency": "EPA Region 3",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 425000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 226610,
        "latitude": 37.5407,
        "longitude": -77.436,
    },
    # ---- Youngstown, OH — SSO (2009) ----
    {
        "case_number": "4:09-cv-02818",
        "registry_id": "110000411833",
        "fips_code": "39099",
        "facility_name": "City of Youngstown — Wastewater Treatment",
        "city": "Youngstown",
        "state": "OH",
        "zip_code": "44503",
        "county": "Mahoning",
        "consent_decree_date": "2009-08-10",
        "compliance_end_date": "2025-08-10",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 190000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 60068,
        "latitude": 41.0998,
        "longitude": -80.6496,
    },
    # ---- Albany, GA — SSO (2010) ----
    {
        "case_number": "1:10-cv-00120",
        "registry_id": "110000465511",
        "fips_code": "13095",
        "facility_name": "City of Albany — Utilities Department",
        "city": "Albany",
        "state": "GA",
        "zip_code": "31701",
        "county": "Dougherty",
        "consent_decree_date": "2010-06-17",
        "compliance_end_date": "2025-06-17",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 195000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 69800,
        "latitude": 31.5785,
        "longitude": -84.1557,
    },
    # ---- Providence, RI — CSO (2008) ----
    {
        "case_number": "1:08-cv-00066",
        "registry_id": "110000397811",
        "fips_code": "44007",
        "facility_name": "Narragansett Bay Commission",
        "city": "Providence",
        "state": "RI",
        "zip_code": "02903",
        "county": "Providence",
        "consent_decree_date": "2008-09-30",
        "compliance_end_date": "2028-09-30",
        "lead_agency": "EPA Region 1",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 800000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 190934,
        "latitude": 41.824,
        "longitude": -71.4128,
    },
    # ---- South Bend, IN — CSO (2012) ----
    {
        "case_number": "3:12-cv-00326",
        "registry_id": "110000540112",
        "fips_code": "18141",
        "facility_name": "City of South Bend — Wastewater Utility",
        "city": "South Bend",
        "state": "IN",
        "zip_code": "46601",
        "county": "St. Joseph",
        "consent_decree_date": "2012-07-11",
        "compliance_end_date": "2028-07-11",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 230000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 103453,
        "latitude": 41.6764,
        "longitude": -86.252,
    },
    # ---- Evansville, IN — CSO (2010) ----
    {
        "case_number": "3:10-cv-00083",
        "registry_id": "110000540033",
        "fips_code": "18163",
        "facility_name": "City of Evansville — Utility Board",
        "city": "Evansville",
        "state": "IN",
        "zip_code": "47708",
        "county": "Vanderburgh",
        "consent_decree_date": "2010-12-01",
        "compliance_end_date": "2030-12-01",
        "lead_agency": "EPA Region 5",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - CSO",
        "penalty_amount": 300000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 117429,
        "latitude": 37.9716,
        "longitude": -87.5711,
    },
    # ---- Augusta, GA — SSO (2008) ----
    {
        "case_number": "1:08-cv-00175",
        "registry_id": "110000465399",
        "fips_code": "13245",
        "facility_name": "Augusta Utilities Department",
        "city": "Augusta",
        "state": "GA",
        "zip_code": "30901",
        "county": "Richmond",
        "consent_decree_date": "2008-12-04",
        "compliance_end_date": "2025-12-04",
        "lead_agency": "EPA Region 4",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 310000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 202081,
        "latitude": 33.4735,
        "longitude": -81.9748,
    },
    # ====================================================================
    # STATE-LEVEL ENFORCEMENT ACTIONS
    # ====================================================================
    # ---- Odessa, TX — TCEQ Agreed Order SSO (2019) ----
    {
        "case_number": "TCEQ-2019-0842-MWD",
        "registry_id": "RN101614661",
        "fips_code": "48135",
        "facility_name": "City of Odessa — Wastewater Collection System",
        "city": "Odessa",
        "state": "TX",
        "zip_code": "79761",
        "county": "Ector",
        "consent_decree_date": "2019-06-14",
        "compliance_end_date": "2025-06-14",
        "lead_agency": "TCEQ",
        "enforcement_level": "State",
        "action_type": "TCEQ Agreed Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 148500.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 123334,
        "latitude": 31.8457,
        "longitude": -102.3676,
    },
    # ---- San Antonio, TX — TCEQ Agreed Order (2020) ----
    {
        "case_number": "TCEQ-2020-0315-MWD",
        "registry_id": "RN101209421",
        "fips_code": "48029",
        "facility_name": "San Antonio Water System — Collection System",
        "city": "San Antonio",
        "state": "TX",
        "zip_code": "78205",
        "county": "Bexar",
        "consent_decree_date": "2020-03-10",
        "compliance_end_date": "2026-03-10",
        "lead_agency": "TCEQ",
        "enforcement_level": "State",
        "action_type": "TCEQ Agreed Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 198000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 1547253,
        "latitude": 29.4241,
        "longitude": -98.4936,
    },
    # ---- Dayton, OH — Ohio EPA DFFOs SSO (2018) ----
    {
        "case_number": "OEPA-DSW-18-03-041",
        "registry_id": "OHD048535381",
        "fips_code": "39113",
        "facility_name": "City of Dayton — Water Reclamation Facility",
        "city": "Dayton",
        "state": "OH",
        "zip_code": "45402",
        "county": "Montgomery",
        "consent_decree_date": "2018-09-20",
        "compliance_end_date": "2026-09-20",
        "lead_agency": "Ohio EPA",
        "enforcement_level": "State",
        "action_type": "Ohio EPA Director's Final Findings & Orders",
        "violation_type": "CWA - SSO",
        "penalty_amount": 305000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 137644,
        "latitude": 39.7589,
        "longitude": -84.1916,
    },
    # ---- Lima, OH — Ohio EPA Consent Order CSO (2017) ----
    {
        "case_number": "OEPA-DSW-17-06-018",
        "registry_id": "OHD048271102",
        "fips_code": "39003",
        "facility_name": "City of Lima — Wastewater Treatment Plant",
        "city": "Lima",
        "state": "OH",
        "zip_code": "45801",
        "county": "Allen",
        "consent_decree_date": "2017-06-15",
        "compliance_end_date": "2025-12-31",
        "lead_agency": "Ohio EPA",
        "enforcement_level": "State",
        "action_type": "Ohio EPA Consent Order",
        "violation_type": "CWA - CSO",
        "penalty_amount": 175000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 36005,
        "latitude": 40.7429,
        "longitude": -84.1053,
    },
    # ---- DeKalb County, GA — Georgia EPD Consent Order SSO (2023) ----
    {
        "case_number": "EPD-WQ-2023-0487",
        "registry_id": "GAD048922110",
        "fips_code": "13089",
        "facility_name": "DeKalb County Department of Watershed Management",
        "city": "Decatur",
        "state": "GA",
        "zip_code": "30030",
        "county": "DeKalb",
        "consent_decree_date": "2023-04-18",
        "compliance_end_date": "2030-04-18",
        "lead_agency": "Georgia EPD",
        "enforcement_level": "State",
        "action_type": "Georgia EPD Consent Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1200000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 764382,
        "latitude": 33.7748,
        "longitude": -84.2963,
    },
    # ---- Augusta-Richmond County, GA — Georgia EPD Admin Order SSO (2019) ----
    {
        "case_number": "EPD-WQ-2019-0221",
        "registry_id": "GAD048922045",
        "fips_code": "13245",
        "facility_name": "Augusta-Richmond County Utilities Department",
        "city": "Augusta",
        "state": "GA",
        "zip_code": "30901",
        "county": "Richmond",
        "consent_decree_date": "2019-08-22",
        "compliance_end_date": "2026-08-22",
        "lead_agency": "Georgia EPD",
        "enforcement_level": "State",
        "action_type": "Georgia EPD Administrative Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 250000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 202081,
        "latitude": 33.4735,
        "longitude": -81.9748,
    },
    # ---- Miami-Dade, FL — FDEP Consent Order SSO (2013) ----
    {
        "case_number": "FDEP-OGC-13-1847",
        "registry_id": "FLD048922301",
        "fips_code": "12086",
        "facility_name": "Miami-Dade Water and Sewer Department",
        "city": "Miami",
        "state": "FL",
        "zip_code": "33128",
        "county": "Miami-Dade",
        "consent_decree_date": "2013-11-05",
        "compliance_end_date": "2025-11-05",
        "lead_agency": "FDEP",
        "enforcement_level": "State",
        "action_type": "FDEP Consent Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1800000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 2701767,
        "latitude": 25.7617,
        "longitude": -80.1918,
    },
    # ---- Fort Lauderdale, FL — FDEP Consent Order (2020) ----
    {
        "case_number": "FDEP-OGC-20-0612",
        "registry_id": "FLD048922415",
        "fips_code": "12011",
        "facility_name": "City of Fort Lauderdale — Public Works Department",
        "city": "Fort Lauderdale",
        "state": "FL",
        "zip_code": "33301",
        "county": "Broward",
        "consent_decree_date": "2020-03-18",
        "compliance_end_date": "2027-03-18",
        "lead_agency": "FDEP",
        "enforcement_level": "State",
        "action_type": "FDEP Consent Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 502000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 182760,
        "latitude": 26.1224,
        "longitude": -80.1373,
    },
    # ---- Imperial Beach/Tijuana, CA — State Water Board CDO (2021) ----
    {
        "case_number": "SWRCB-WQ-2021-0018-CDO",
        "registry_id": "CAD048922501",
        "fips_code": "06073",
        "facility_name": "City of Imperial Beach — Cross-Border Sewage",
        "city": "Imperial Beach",
        "state": "CA",
        "zip_code": "91932",
        "county": "San Diego",
        "consent_decree_date": "2021-07-20",
        "compliance_end_date": "2029-07-20",
        "lead_agency": "State Water Board",
        "enforcement_level": "State",
        "action_type": "State Water Board CDO",
        "violation_type": "CWA - SSO",
        "penalty_amount": 0.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 27342,
        "latitude": 32.5840,
        "longitude": -117.1131,
    },
    # ---- Los Angeles, CA — LA Regional Water Board CAO SSO (2015) ----
    {
        "case_number": "LARWQCB-2015-0024-CAO",
        "registry_id": "CAD048922610",
        "fips_code": "06037",
        "facility_name": "City of Los Angeles — Bureau of Sanitation",
        "city": "Los Angeles",
        "state": "CA",
        "zip_code": "90012",
        "county": "Los Angeles",
        "consent_decree_date": "2015-05-12",
        "compliance_end_date": "2025-05-12",
        "lead_agency": "LA Regional Water Board",
        "enforcement_level": "State",
        "action_type": "Regional Water Board CAO",
        "violation_type": "CWA - SSO",
        "penalty_amount": 2000000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 3898747,
        "latitude": 34.0522,
        "longitude": -118.2437,
    },
    # ---- Scranton, PA — PA DEP Consent Order CSO (2016) ----
    {
        "case_number": "PADEP-CWM-2016-0043",
        "registry_id": "PAD048922701",
        "fips_code": "42069",
        "facility_name": "Scranton Sewer Authority",
        "city": "Scranton",
        "state": "PA",
        "zip_code": "18503",
        "county": "Lackawanna",
        "consent_decree_date": "2016-10-04",
        "compliance_end_date": "2026-10-04",
        "lead_agency": "PA DEP",
        "enforcement_level": "State",
        "action_type": "PA DEP Consent Order",
        "violation_type": "CWA - CSO",
        "penalty_amount": 400000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 76997,
        "latitude": 41.4090,
        "longitude": -75.6624,
    },
    # ---- Reading, PA — PA DEP Administrative Order SSO (2018) ----
    {
        "case_number": "PADEP-CWM-2018-0091",
        "registry_id": "PAD048922802",
        "fips_code": "42011",
        "facility_name": "City of Reading — Wastewater System",
        "city": "Reading",
        "state": "PA",
        "zip_code": "19601",
        "county": "Berks",
        "consent_decree_date": "2018-04-17",
        "compliance_end_date": "2025-04-17",
        "lead_agency": "PA DEP",
        "enforcement_level": "State",
        "action_type": "PA DEP Administrative Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 200000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 95112,
        "latitude": 40.3356,
        "longitude": -75.9269,
    },
    # ---- Terre Haute, IN — IDEM Agreed Order SSO (2017) ----
    {
        "case_number": "IDEM-2017-W-0218",
        "registry_id": "IND048922901",
        "fips_code": "18167",
        "facility_name": "City of Terre Haute — Wastewater Utility",
        "city": "Terre Haute",
        "state": "IN",
        "zip_code": "47807",
        "county": "Vigo",
        "consent_decree_date": "2017-08-23",
        "compliance_end_date": "2025-08-23",
        "lead_agency": "IDEM",
        "enforcement_level": "State",
        "action_type": "IDEM Agreed Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 350000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 58389,
        "latitude": 39.4667,
        "longitude": -87.4139,
    },
    # ---- Hammond, IN — IDEM Consent Order CSO (2015) ----
    {
        "case_number": "IDEM-2015-W-0105",
        "registry_id": "IND048923001",
        "fips_code": "18089",
        "facility_name": "City of Hammond — Sanitary District",
        "city": "Hammond",
        "state": "IN",
        "zip_code": "46320",
        "county": "Lake",
        "consent_decree_date": "2015-11-09",
        "compliance_end_date": "2025-11-09",
        "lead_agency": "IDEM",
        "enforcement_level": "State",
        "action_type": "IDEM Consent Order",
        "violation_type": "CWA - CSO",
        "penalty_amount": 275000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 77879,
        "latitude": 41.5834,
        "longitude": -87.5001,
    },
    # ---- Prichard, AL — ADEM Consent Order SSO (2019) ----
    {
        "case_number": "ADEM-2019-171-CWA",
        "registry_id": "ALD048923101",
        "fips_code": "01097",
        "facility_name": "City of Prichard — Water Works and Sewer Board",
        "city": "Prichard",
        "state": "AL",
        "zip_code": "36610",
        "county": "Mobile",
        "consent_decree_date": "2019-05-14",
        "compliance_end_date": "2026-05-14",
        "lead_agency": "ADEM",
        "enforcement_level": "State",
        "action_type": "ADEM Consent Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 500000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 19073,
        "latitude": 30.7385,
        "longitude": -88.0784,
    },
    # ---- Gulfport, MS — MDEQ Administrative Order SSO (2020) ----
    {
        "case_number": "MDEQ-WPC-2020-0054",
        "registry_id": "MSD048923201",
        "fips_code": "28047",
        "facility_name": "City of Gulfport — Wastewater Division",
        "city": "Gulfport",
        "state": "MS",
        "zip_code": "39501",
        "county": "Harrison",
        "consent_decree_date": "2020-02-27",
        "compliance_end_date": "2026-02-27",
        "lead_agency": "MDEQ",
        "enforcement_level": "State",
        "action_type": "MDEQ Administrative Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 150000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 72926,
        "latitude": 30.3674,
        "longitude": -89.0928,
    },
    # ---- Knoxville, TN — TDEC Consent Order (supplement) (2018) ----
    {
        "case_number": "TDEC-WPC-2018-0331",
        "registry_id": "TND048923301",
        "fips_code": "47093",
        "facility_name": "City of Knoxville — Wastewater Collection System",
        "city": "Knoxville",
        "state": "TN",
        "zip_code": "37902",
        "county": "Knox",
        "consent_decree_date": "2018-07-11",
        "compliance_end_date": "2026-07-11",
        "lead_agency": "TDEC",
        "enforcement_level": "State",
        "action_type": "TDEC Consent Order",
        "violation_type": "CWA - CSO/SSO",
        "penalty_amount": 300000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 190740,
        "latitude": 35.9606,
        "longitude": -83.9207,
    },
    # ---- Camden County, NJ — NJDEP ACO CSO (2016) ----
    {
        "case_number": "NJDEP-WPE-2016-0088",
        "registry_id": "NJD048923401",
        "fips_code": "34007",
        "facility_name": "Camden County Municipal Utilities Authority",
        "city": "Camden",
        "state": "NJ",
        "zip_code": "08101",
        "county": "Camden",
        "consent_decree_date": "2016-05-23",
        "compliance_end_date": "2026-05-23",
        "lead_agency": "NJDEP",
        "enforcement_level": "State",
        "action_type": "NJDEP Administrative Consent Order",
        "violation_type": "CWA - CSO",
        "penalty_amount": 800000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 73562,
        "latitude": 39.9259,
        "longitude": -75.1196,
    },
    # ---- Charleston, WV — WV DEP Consent Order CSO (2014) ----
    {
        "case_number": "WVDEP-2014-WV-0072",
        "registry_id": "WVD048923501",
        "fips_code": "54039",
        "facility_name": "City of Charleston — Sanitary Board",
        "city": "Charleston",
        "state": "WV",
        "zip_code": "25301",
        "county": "Kanawha",
        "consent_decree_date": "2014-09-08",
        "compliance_end_date": "2025-09-08",
        "lead_agency": "WV DEP",
        "enforcement_level": "State",
        "action_type": "WV DEP Consent Order",
        "violation_type": "CWA - CSO",
        "penalty_amount": 200000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 46536,
        "latitude": 38.3498,
        "longitude": -81.6326,
    },
    # ---- Flint, MI — EGLE ACO SSO/water (2022) ----
    {
        "case_number": "EGLE-WRD-2022-0041",
        "registry_id": "MID048923601",
        "fips_code": "26049",
        "facility_name": "City of Flint — Water Service Center",
        "city": "Flint",
        "state": "MI",
        "zip_code": "48502",
        "county": "Genesee",
        "consent_decree_date": "2022-01-19",
        "compliance_end_date": "2029-01-19",
        "lead_agency": "EGLE",
        "enforcement_level": "State",
        "action_type": "EGLE Administrative Consent Order",
        "violation_type": "CWA - SSO",
        "penalty_amount": 100000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 97310,
        "latitude": 43.0125,
        "longitude": -83.6875,
    },
    # ---- St. Thomas, VI — VIWMA Wastewater Violations (2011) ----
    {
        "case_number": "1:11-cv-00010",
        "registry_id": "VI0020001",
        "fips_code": "78030",
        "facility_name": "Virgin Islands Waste Management Authority (VIWMA)",
        "city": "St. Thomas",
        "state": "VI",
        "zip_code": "00802",
        "county": "St. Thomas",
        "consent_decree_date": "2011-09-30",
        "compliance_end_date": "2028-09-30",
        "lead_agency": "EPA Region 2",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "CWA - SSO",
        "penalty_amount": 1875000.0,
        "statute": "CWA",
        "pipe_infrastructure_flag": True,
        "population": 51634,
        "latitude": 18.3358,
        "longitude": -64.9307,
    },
    # ---- Hagatna, GU — Guam Waterworks Authority SDWA (2003) ----
    {
        "case_number": "1:02-cv-00065",
        "registry_id": "GU0000003",
        "fips_code": "66010",
        "facility_name": "Guam Waterworks Authority (GWA)",
        "city": "Hagatna",
        "state": "GU",
        "zip_code": "96910",
        "county": "Guam",
        "consent_decree_date": "2003-05-15",
        "compliance_end_date": "2029-12-31",
        "lead_agency": "EPA Region 9",
        "enforcement_level": "Federal",
        "action_type": "Consent Decree",
        "violation_type": "SDWA - Public Water System",
        "penalty_amount": 300000.0,
        "statute": "SDWA",
        "pipe_infrastructure_flag": True,
        "population": 170534,
        "latitude": 13.4443,
        "longitude": 144.7937,
    },
]

# ---------------------------------------------------------------------------
# Enrich records with calculated fields
# ---------------------------------------------------------------------------


def build_records() -> list:
    """Compute days_to_deadline, urgency_tier, and last_updated."""
    records = []
    for r in RAW_DECREES:
        days, tier = calc_urgency(r["compliance_end_date"])
        rec = dict(r)
        rec["days_to_deadline"] = days
        rec["urgency_tier"] = tier
        rec["case_status"] = "Active"
        rec["last_updated"] = NOW_TS
        records.append(rec)
    return records


# ---------------------------------------------------------------------------
# BigQuery MERGE (same pattern as etl.py)
# ---------------------------------------------------------------------------


def load_to_bigquery(records: list):
    """MERGE seed records into BigQuery using temp-table + MERGE pattern."""
    from google.cloud import bigquery

    project_id = os.getenv("GCP_PROJECT_ID")
    if not project_id:
        raise RuntimeError("GCP_PROJECT_ID not set")

    client = bigquery.Client(project=project_id)
    dataset_id = f"{project_id}.ipi_intelligence"
    table_id = f"{dataset_id}.consent_decrees"

    # Ensure dataset + table exist
    dataset = bigquery.Dataset(dataset_id)
    dataset.location = "US"
    client.create_dataset(dataset, exists_ok=True)
    print(f"  Dataset {dataset_id} ready")

    schema = [bigquery.SchemaField(name, dtype) for name, dtype in BQ_SCHEMA]
    table = bigquery.Table(table_id, schema=schema)
    client.create_table(table, exists_ok=True)

    # Schema evolution
    existing_table = client.get_table(table_id)
    existing_names = {f.name for f in existing_table.schema}
    new_fields = [f for f in schema if f.name not in existing_names]
    if new_fields:
        updated_schema = list(existing_table.schema) + new_fields
        existing_table.schema = updated_schema
        client.update_table(existing_table, ["schema"])
        print(f"  Updated table schema with {len(new_fields)} new columns")

    print(f"  Table {table_id} ready")

    # Temp table + MERGE
    temp_table_id = f"{dataset_id}._temp_seed_{int(time.time())}"
    temp_table = bigquery.Table(temp_table_id, schema=schema)
    client.create_table(temp_table, exists_ok=True)

    errors = client.insert_rows_json(temp_table_id, records)
    if errors:
        client.delete_table(temp_table_id, not_found_ok=True)
        raise RuntimeError(f"BigQuery insert errors: {errors}")

    merge_cols = [name for name, _ in BQ_SCHEMA if name != "case_number"]
    update_clause = ", ".join(f"T.{c} = S.{c}" for c in merge_cols)
    insert_cols = ", ".join(name for name, _ in BQ_SCHEMA)
    insert_vals = ", ".join(f"S.{name}" for name, _ in BQ_SCHEMA)

    merge_sql = f"""
    MERGE `{table_id}` T
    USING `{temp_table_id}` S
    ON T.case_number = S.case_number
    WHEN MATCHED THEN
        UPDATE SET {update_clause}
    WHEN NOT MATCHED THEN
        INSERT ({insert_cols})
        VALUES ({insert_vals})
    """

    print("  Executing MERGE...")
    query_job = client.query(merge_sql)
    query_job.result()
    rows_affected = query_job.num_dml_affected_rows or 0
    print(f"  MERGE complete — {rows_affected} rows affected")

    client.delete_table(temp_table_id, not_found_ok=True)
    return rows_affected


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("IPI Consent Decree — Seed Data Loader")
    print("=" * 60)

    records = build_records()
    print(f"\nPrepared {len(records)} seed consent decree records")

    # Summary by urgency tier
    tiers = {}
    for r in records:
        t = r["urgency_tier"]
        tiers[t] = tiers.get(t, 0) + 1
    print("\nUrgency tier breakdown:")
    for tier in ["OVERDUE", "CRITICAL", "ACTIVE", "MONITORING"]:
        if tier in tiers:
            print(f"  {tier:12s}: {tiers[tier]}")

    # Summary by state
    states = {}
    for r in records:
        states[r["state"]] = states.get(r["state"], 0) + 1
    print(f"\nStates covered: {len(states)}")
    print(f"  {', '.join(sorted(states.keys()))}")

    # Total penalties
    total_penalty = sum(r["penalty_amount"] for r in records)
    print(f"\nTotal penalty amounts: ${total_penalty:,.2f}")

    print("\nLoading to BigQuery...")
    rows = load_to_bigquery(records)

    print("\n" + "=" * 60)
    print(f"DONE — {rows} rows merged into BigQuery")
    print("=" * 60)


if __name__ == "__main__":
    main()
